### ISSUE TITLE
moving coordination server

### ISSUE THREAD

**Issue by linuxd3v** [tonarino/innernet#112]
Lets say I've setup  an innernet network successfully with 4-5 cidrs and  2 dozens servers an suddenly my coordination server goes down.
How would I handle restoring it? 
Would I just spin up another vps, copy db file and re-install **innernet** server and relaunch it  - would that be it?

**Comment by mcginty** [comment]
Yep, exactly. If the external IP changes, you'll also have to update the `external-endpoint` in your `/etc/innernet/[network].conf`.

The coordinating server uses a simple SQLite database, so you can also take easy backups a la:
```bash
sqlite3 /var/lib/innernet-server/mynetwork.db ".backup mynetwork.db.bak"
```

Peers that are already connected to each other will remain connected to each other while the the coordinating server is down, but peers trying to join the network won't be able to obviously until it's back up.

Hope that helps! I'm interested to hear other ideas on other simple ways to make innernet more high-availability for more use cases (or ways to make backups even simpler). For our case at tonari, the coordinating server going down for a small period of time is not a major issue (although I'm happy all the same it has yet to go down) since our peers will remain connected and continue streaming to each other, so we opted initially to keep code complexity down and not offer HA solutions.

**Comment by linuxd3v** [comment]
@mcginty Thank you! 
this seems fairly simple and maintainable to handle server fallout (at least at my current scale).
appreciate you finding the time to opensource this and share with the community :+1:

**Comment by maaft** [comment]
I see two options for kubernetes deployment:
Option1:
- replace file-based sqlite with distributed sqlite like [rqlite](https://github.com/rqlite/rqlite)
- host multiple innernet-servers behind loadbalancer
- if one node goes down, mutlple other nodes are still available to handle requests

Option2:
- use persistent distributed storage to store sqlite files
- run single innernet-server with attached kubernetes-service
- if pod goes down, it'll get restarted automatically and storage gets reattached

Personally, I believe that Option2 is faster to achieve without doing any changes to innernets codebase.

Any thoughts?

**Comment by Shonke** [comment]
> I see two options for kubernetes deployment: Option1:
> 
> * replace file-based sqlite with distributed sqlite like [rqlite](https://github.com/rqlite/rqlite)
> * host multiple innernet-servers behind loadbalancer
> * if one node goes down, mutlple other nodes are still available to handle requests
> 
> Option2:
> 
> * use persistent distributed storage to store sqlite files
> * run single innernet-server with attached ingress node
> * if pod goes down, it'll get restarted automatically and storage gets reattached
> 
> Personally, I believe that Option2 is faster to achieve without doing any changes to innernets codebase.
> 
> Any thoughts?

What about the idea of using dns record as seed?
