### ISSUE TITLE
Peers cannot reach each other within or between CIDRs

### ISSUE THREAD

**Issue by bowen-song** [tonarino/innernet#117]
### Discussed in https://github.com/tonarino/innernet/discussions/116

<div type='discussions-op-text'>

<sup>Originally posted by **bowen-song** July 21, 2021</sup>
Hi!
Just want to start off by saying this is a very neat project, and thanks!

Now onto the problem I'm having.
Setup: 
`sudo inn list --tree`
```
bween
  10.42.0.0/16 bween
    10.42.0.1/32 innernet-server
    | ◉ 10.42.0.1: innernet-server 
    10.42.1.0/24 users
    | ◉ 10.42.1.1: archxps
    | ◯ 10.42.1.2: mbp 
    10.42.2.0/24 servers
    | ◯ 10.42.2.1: media-server

```
`sudo inn list-associations bween`
```
[*] Fetching CIDRs
[*] Fetching associations
1: users <=> servers
```

I've followed the documentation to the best of my understanding and there weren't any errors while installing, but when attempting to connect between peers, the only connection that works is between peer and "innernet server" located at 10.42.0.1; all other connections never make it.

As an example from `archxps`:
`ping innernet-server.bween.wg` -> okay
`ping mbp.bween.wg` -> no connection
`ping media-server.bween.wg` -> no connection

I've tried pinging with the direct ip address and that hasn't worked either so I don't believe it's a DNS problem.

For additional details, `innernet-server` is hosted on a vps, and has a public facing wg port, while all users/servers are behind a local OpenWrt router with no open/listen ports. 

I'm not sure if the NAT holepunching method is the same with innernet as it is with Tailscale, but in case it helps troubleshoot, I have run Tailscale on these machines with no problems so I think I must be setting something up wrong (I just can't figure out what it is!!).

Thanks!</div>

**Comment by mcginty** [comment]
Hey @bowen-song, that does indeed sound like a NAT holepunching issue - innernet currently has significantly less robust NAT holepunching logic compared to tailscale: see #115 and #109.

Specifically, the issue that you're running into is that innernet also doesn't support ICE-esque enumeration of local IP addresses, so if your router doesn't support "NAT hairpinning," as it's called, then connections won't work without open ports.

I'm actively working on writing some solutions to try to improve connectivity in the P2P case (a later goal will be to implement relays that can proxy traffic like a TURN server, which Tailscale also implements). In the mean time, you can look into enabling NAT hairpinning/loopback or opening ports, otherwise I'll fill you in when more work is done that would help this situation out.

**Comment by bowen-song** [comment]
Hi @mcginty, thanks for the quick response and links to the other reading.
Unfortunately, I'm not super well versed with OpenWrt on the router so it looks like more tinkering is in order when I have the time. In case you are able to implement the ICE-like functionality before I figure this out, I would appreciate a ping when you've got it figured out! Any timeline on when you guys might have this functionality implemented?

**Comment by mcginty** [comment]
@bowen-song sounds good. I've started the work of improving our NAT holepunching situation in #118, and once that's in I'll be taking a look at ICE-esque negotiation and will try to remember to ping on this thread about the state of that :).

I'll close this in the meantime in favor of the existing NAT tracking issues. Thanks for opening this!

**Comment by bowen-song** [comment]
I appreciate it lots! Thank you 😃

**Comment by daniel9jonas** [comment]
is this issue solved? i have exactly the same configuration and still not able to reach peers inter/between CIDR. hosting innernet on aws lightsail with open wg port and having a user behind openWrt router with closed ports. thanks
