### ISSUE TITLE
Innernet server not reachable to redeem invite

### ISSUE THREAD

**Issue by ArdaXi** [tonarino/innernet#189]
I ran into a weird issue trying to set up innernet earlier. Let me just run through the steps I took.

I set up (IPv6) CIDRs and created a peer invite on my server, then ran `innernet-server serve` which successfully set up Wireguard there.

I then moved the invite to my laptop and tried `innernet install invite.toml`. This times on out "Registering keypair on server." To rule out firewall issues I restarted the install but killed it before it timed out, which keeps the Wireguard connection in place. Then, on the server I ran `tcpdump` on the Wireguard interface.

What I see is that if I curl to the innernet server, the server receives the TCP SYN from Wireguard, but never responds with an ACK, so my curl retransmits for a bit then gives up. Running curl on port 80 and 443 where I have an nginx server running through Wireguard does yield a result, and the packet capture shows a normal TCP handshake followed by HTTP data.

This suggests to me that the issue is with the innernet API server specifically, but even `RUST_LOG=debug` stays silent when I try to connect, so I'm kind of stuck. Any idea what I could do to narrow down what's causing this?

**Comment by mcginty** [comment]
Well that sounds annoying!

So it sounds like it's not a routing problem since the client and server have successfully completed a TCP handshake over the wireguard interface if I'm understanding correctly. Ping should also work (i.e. `ping innernet-server.[mynetworkname].wg`).

Assuming you kept the default listening port for your server (51820), double-check that HTTP traffic over 51820 is allowed within the wireguard interface.

For your client, could you run `innernet -vv install invite.toml` and see if that provides any more useful output? The extra verbosity flags should help give more info about where the request gets stuck.

Similarly, for sanity-checking the server, can you curl the server from the server itself via its innernet IP? This request should return a 401 Unauthorized error.
```bash
curl -v [fd00::1]:51820/v1/user/state
```
(substituting the IP for the correct one, of course).

**Comment by ArdaXi** [comment]
> Ping should also work (i.e. ping innernet-server.[mynetworkname].wg).

I'm not using the hosts file editing, but pinging the server from the client over the Wireguard interface works, yes. The other way around also.

> Assuming you kept the default listening port for your server (51820), double-check that HTTP traffic over 51820 is allowed within the wireguard interface.

iptables rules are in place to allow both TCP and UDP on the listening port _and_ the subnet the client is using. The exact same rule that's allowing 80/443 through, which does work.

> For your client, could you run innernet -vv install invite.toml and see if that provides any more useful output? The extra verbosity flags should help give more info about where the request gets stuck.

None, I'm afraid.

```
[D] [ureq::stream] connecting to [fd1b:48cd:e05e::1]:51444 at [fd1b:48cd:e05e::1]:51444
[E] failed to start the interface: http://[fd1b:48cd:e05e::1]:51444/v1/user/redeem: Connection Failed: Connect error: connection timed out.
```

> Similarly, for sanity-checking the server, can you curl the server from the server itself via its innernet IP? This request should return a 401 Unauthorized error.

Yup:

```
*   Trying fd1b:48cd:e05e::1:51444...
* Connected to fd1b:48cd:e05e::1 (fd1b:48cd:e05e::1) port 51444 (#0)
> GET /v1/user/state HTTP/1.1
> Host: [fd1b:48cd:e05e::1]:51444
> User-Agent: curl/7.80.0
> Accept: */*
>
* Mark bundle as not supporting multiuse
< HTTP/1.1 401 Unauthorized
< content-length: 0
< date: Sun, 23 Jan 2022 18:04:35 GMT
```

**Comment by mcginty** [comment]
One last sanity check, which I assume will be a "connection failed" - running `curl fd1b:48cd:e05e::1:51444/v1/user/state` also doesn't work, yes? Just want to rule out the HTTP library within the `innernet` binary being suspect.

Another thing to note for your firewall rules since I don't know exactly what your setup is - `innernet-server` not only binds to its IP address, but specifically to the wireguard interface to forbit any rogue un-authenticated packets, so if any of your firewall rules are interface-specific that could be causing issues compared to successfully running curl against a server that's only bound to `::` on all interfaces.

**Comment by ArdaXi** [comment]
> One last sanity check, which I assume will be a "connection failed" - running curl fd1b:48cd:e05e::1:51444/v1/user/state from the client that's trying to join the network also doesn't work, yes?

Yeah, that's what I did to get a pcap in the first place. That results in SYN but no ACK.

> Another thing to note for your firewall rules since I don't know exactly what your setup is 

Well, [here's my config](https://gist.github.com/ArdaXi/3fd2fe6587d3b7ddb1eacff74fa66b9b). I'd expect both line 85 and line 144 to be letting it through. `street` is the name of the Wireguard interface.

**Comment by mcginty** [comment]
> Yeah, that's what I did to get a pcap in the first place. That results in SYN but no ACK.

Gotcha, sorry I misread. If you use `RUST_LOG=trace` on the server, does that provide any evidence at all that the server got any kind of connection attempt?

> Well, [here's my config](https://gist.github.com/ArdaXi/3fd2fe6587d3b7ddb1eacff74fa66b9b). I'd expect both line 85 and line 144 to be letting it through. `street` is the name of the Wireguard interface.

Nothing looks immediately suspicious to me, but I wouldn't claim to be talented enough to guarantee it's not the iptables that are the problem, you could look at some of the suggestions in https://serverfault.com/questions/78240/debugging-rules-in-iptables to see if there are any rules causing packets to be dropped unexpectedly...

Also, just to confirm, what version of innernet and innernet-server are you using?

**Comment by ArdaXi** [comment]
Okay, well, this turns out to be an issue on my end after all. NixOS at some point switched from iptables to nf_tables, which left a legacy table behind that didn't incorporate my changes. Sorry for wasting your time...

**Comment by mcginty** [comment]
You're good! At least I'll have this solution in my memory if anyone else runs into this.

**Comment by ArdaXi** [comment]
I also appreciate the quick responses. In the interest of said memory: I eventually tracked this by running `iptables-legacy -L`. The presence of that command in the first place, a difference between output of `iptables -L` and `iptables-legacy -L` or the (in hindsight rather obvious)

```
# Warning: iptables-legacy tables present, use iptables-legacy to see them
```

comment at the top of `iptables -L` output are clear signs that something like this is going on.

In which case it would be solved by clearing the legacy tables (`iptables-legacy -F; iptables-legacy -X`) assuming the new rules are what's desired.
