### ISSUE TITLE
Bypass confirmation when uninstalling

### ISSUE THREAD

**Issue by bermi** [tonarino/innernet#190]
Thank you for creating innernet

I'm trying to automatically setup and tear down innernet and found some issues that prevent my setup from being fully automated.

There's no `--yes` option for the `innernet-server uninstall evilcorp` command.

I tried piping the response like `echo 'y' | innernet-server uninstall evilcorp` or using the `yes` command `yes innernet-server uninstall evilcorp` but none of them work as expected.

Would it be possible to enable the `--yes` option when uninstalling?

**Comment by bschwind** [comment]
Hey, thanks for trying innernet!

It seems you're right that the `uninstall` command doesn't let you bypass the confirmation and I'm not 100% sure if that's by design.

In any case, it would be quite easy to add the flag:

* Add a `yes` field struct here: https://github.com/tonarino/innernet/blob/e11b73972c40652d9e83686ed3ea0757b9639eb0/server/src/main.rs#L74
  * Example of a `yes` field: https://github.com/tonarino/innernet/blob/main/shared/src/types.rs#L346-L348
* Modify this if statement to short-circuit if the `yes` flag is passed: https://github.com/tonarino/innernet/blob/e11b73972c40652d9e83686ed3ea0757b9639eb0/server/src/main.rs#L417-L424

I'll wait for @mcginty to weigh in first before adding it, as it may have been intentionally omitted.

**Comment by bermi** [comment]
@bschwind makes sense to omit it by design to avoid human errors.

It looks like other destructive commands such as `innernet delete-association` also require human interaction, which leads to messing with the DB directly to automate things.

Just for some context, our goal is to have static manifests checked into source control for defining _cidrs_, _peers_ and _associations_. Then a script consolidates the manifest with the `innernet-server` to revert any change that's not in the code. Right now, we are updating the DB directly to achieve this goal.

**Comment by mcginty** [comment]
Sorry for the delay - I fixed this in master and this will be in the 1.5.3 release :). I added a `--yes` flag for uninstall, as well as making it possible to add and delete associations in scripts as well.
