### ISSUE TITLE
Replace wireguard-go backend with boringtun?

### ISSUE THREAD

**Issue by colemickens** [tonarino/innernet#34]
Hi,

While reading the "Windows support" issue, I saw a comment implying that wireguard-go must be used for a userspace implementation. I recalled that Cloudflare has their own userspace implementation, in Rust no less.

Is there interest in adopting `boringtun`? Either in pursuit of Windows support, or for its own merits?

Cheers, and thanks for building/releasing/maintaining `innernet`!

**Comment by mcginty** [comment]
Hey @colemickens,

The userspace implementations should be easily swappable (right now it's hardcoded in innernet to look for `wireguard-go`, but that should be changed to look for an environment variable with an override), so innernet thankfully doesn't have to choose one and force everyone to use it. It should be as easy as `USERSPACE_WG=boringtun innernet up <network>`.

As for `boringtun` specifically, it's not an official WireGuard project so I'm not personally interested in setting it as the default, even though it's written in Rust 😉. As a side note, there's an [official Rust implementation in the works](https://git.zx2c4.com/wireguard-rs/) that I'd be excited to switch to once it's ready for prime time.

**Comment by colemickens** [comment]
Thanks @mcginty !

**Comment by mcginty** [comment]
No problem @colemickens! As noted in the PR, `boringtun` specifically doesn't work with `innernet` since its configuration protocol handling seems broken (possibly related to https://github.com/cloudflare/boringtun/issues/163, but we do in fact send the private key before peers). If you can swing it, I'd recommend sticking with `wireguard-go` to ensure correctness.
