### ISSUE TITLE
Serverless setup

### ISSUE THREAD

**Issue by calderonth** [tonarino/innernet#39]
Hi,

I like the project ideas and goal but I'm wondering how things could be refactored to allow for a serverless setup.

My understanding is that the API/server logic is being wireguard when it could be hosted on a serverless platform (I'm thinking of Cloudflare Workers).
The initial invite logic could be substituted by oneshot API tokens and it would be relatively easy to leverage SSO/IdP and other features without having to do a lot of work.

Is this something that was explored during the design of innernet?

Cheers

**Comment by calderonth** [comment]
Am I missing something fundamentally obvious that would make this impossible?

**Comment by mcginty** [comment]
@calderonth we didn't explore any of these lambda function options too deeply because it typically requires a lot more vendor-specific code compared to just expecting a plain old server. That said, I'm not aware of any "serverless" platform providers that can run WireGuard interfaces...

The long story short is that, at a minimum, innernet needs a centralized database to manage IP address allocation, since it doesn't do distributed negotiation of addresses.

**Comment by calderonth** [comment]
Thanks for your reply.

This is where I was missing some context even with the blog post details.
I understand the innernet server is used as the endpoint for the API frontend/DB backend and is sitting behind Wireguard.
Innernet clients then connect via Wireguard and can fetch their respective configuration from the server.

However, what is the underlying wireguard topology? Does the innernet server behaves as a VPN concentrator or is the network more of a mesh?

If it's a mesh, then it would be feasable to split the architecture:

- control plane: expose (securely) the API/DB backend without Wireguard hosted on a serverless platform, have clients authenticate/pull their config
- data plane: the config is used by client to setup tunnels and access the various networks

If I go back to my serverless example, Cloudflare Workers supports a K/V storage backend (not SQL-type) and that would be enough to store innernet configuration.

**Comment by mcginty** [comment]
Innernet is mesh-like - the server doesn't do any proxying of actual traffic, only coordinating connections between peers.

You could certainly make a control server that didn't use WireGuard at all, but I find it very convenient personally to do everything within a WireGuard network to limit the externally exposed surface.

I don't think Cloudflare Workers over TLS instead of WireGuard is something I'm particularly interested in supporting in the innernet project, but you are of course welcome to fork it and do it yourself!

**Comment by calderonth** [comment]
Alright thanks for the clarification :-).
I might investigate a fork but already have loads of side projects ;-)

**Comment by mcginty** [comment]
No problem! Best of luck on your projects, whichever you choose :P.

I'm gonna go ahead and close this, but definitely let me know if you decide to take on that fork project.
