### ISSUE TITLE
innernet-server deb should depend on and modprobe wireguard

### ISSUE THREAD

**Issue by mrdomino** [tonarino/innernet#5]
I needed to `modprobe wireguard` (and `apt install wireguard`) in order for `innernet-server serve` to work.

Not sure what the most morally correct way is to do this persistently. I wound up doing `echo wireguard > /etc/modules-load.d/wireguard.conf`.

**Comment by mcginty** [comment]
Ah right - this is an issue for anyone with Linux kernels < 5.6.

I'm also not sure of the canonical way packages solve this - I'll have to look for other examples out there. If other packages just add a file `/etc/modules-load.d/` I'm more than happy to do that too.

**Comment by mrdomino** [comment]
Sounds reasonable. Congrats on the launch, btw.

**Comment by mcginty** [comment]
Thanks, and thanks so much for trying it out and testing it! I appreciate you opening the issue.

**Comment by Nemo157** [comment]
Appears to be an issue on 5.11 too, `/sys/module/wireguard` didn't exist until I did `modprobe wireguard` to load it

```
Linux 5.11.10-arch1-1 #1 SMP PREEMPT Fri, 26 Mar 2021 00:11:29 +0000 x86_64 GNU/Linux
```

**Comment by Nemo157** [comment]
Dropping in a `modules-load.d` seems to be done by at least a couple of packages on arch:

```console
> pacman -Fx '^etc/modules-load\.d/.+'
etc/modules-load.d/i2c_dev.conf is owned by community/deepin-daemon 5.12.52-1
etc/modules-load.d/deepin-screen-recorder.conf is owned by community/deepin-screen-recorder 5.8.1-1
etc/modules-load.d/zfs.conf is owned by archzfs/zfs-utils 2.0.4-1
etc/modules-load.d/zfs.conf is owned by archzfs/zfs-utils-git 2021.03.26.r6649.g38280c352-1
etc/modules-load.d/zfs.conf is owned by archzfs/zfs-utils-rc 2.0.0_rc7-1
```

**Comment by mcginty** [comment]
I've opted for calling `/sbin/modprobe wireguard` in `wgctrl-rs` for now to divorce us from needing package managers to make the kernel module load properly.

I'm going to re-open this though since I'd like for `innernet` to be able to run without root and just use `CAP_NET_ADMIN`, at which point loading modules from the binary wouldn't work (and rightly so 🙂). 

If the current solution is problematic in some other way I'm unaware of, please let me know.

**Comment by mk-fg** [comment]
> I'm going to re-open this though since I'd like for innernet to be able to run without root and just use CAP_NET_ADMIN, at which point loading modules from the binary wouldn't work (and rightly so slightly_smiling_face).
> If the current solution is problematic in some other way I'm unaware of, please let me know.

It doesn't work in containers with kernel wg implementation.
WireGuard can be used in these just fine, but there's no kernel or its modules there, and at least with systemd-nspawn, there's no `/sys/module/wireguard` path either.

This makes it impossible to start innernet in containers with kernel wireguard implementation because of this exists() check, as both operations it does are guaranteed to fail there, even though e.g. `ip link add wg type wireguard` will work without issues and kernel module is perfectly usable - just a problem with this check.

Bypassing it completely with something like:
```
pub fn exists() -> bool {
    return true;
```
...allows both server and client to work without issues.

I'd suggest adding e.g `--backend=kernel` option which would allow to bypass modprobe and auto-detection checks, to avoid falling back to userspace implementation (and getting additional confusing errors from there), or potentially the opposite - ignore kernel implementation and the need for uid=root and go straight for wireguard-go.

**Comment by mcginty** [comment]
I'm going to go with this option, I like the idea of having a backend flag.

Will also look into what the `iproute2` tool is doing in the background when adding a WireGuard interface.

**Comment by mcginty** [comment]
The latest innernet neither runs modprobe internally nor does it do existence checks for the kernel module since it's too unreliable across different environments. Instead, you can manually specify `--backend userspace` on Linux to force the userspace backend, otherwise it assumes the kernel module exists.

This behavior feels more similar to how WireGuard itself supports the userspace implementation on Linux - it's not recommended and only advanced users should be relying on it (this applies in the context of a container, too, for example).
