### ISSUE TITLE
Feature Request - Ability to rename a peer

### ISSUE THREAD

**Issue by kbknapp** [tonarino/innernet#87]
Is there a current way to rename a peer? Or if not, that would be a feature we'd (where we're testing `innernet` for use at work) find useful. 

We understand the security implications of having immutable publickey/private IP tuples, which is fine. But we've run into a few instances were we need to move a peer and end up with cidrs full of peers like `foo`, `foo_take2`, `foo_take3`, etc. It'd be nice to be able to disable `foo`, then rename to `diasabled` (or whatever), and then create a new `foo` peer. This way we don't have cidrs full of confusing names (since we could later do something like filter by disabled, or even just `grep -v`, etc.)

I could see how some could say a DNS hostname suddenly changing private IP/public key could be an issue, however I'd argue that since the new public key/private IP tuple is valid on the wireguard network, and has a valid association you should be assuming it's safe anyways.

**Comment by Eeems** [comment]
You could always modify the sqlite database to rename them and then have all peers run `inn fetch` as a temporary workaround.

**Comment by mcginty** [comment]
As a matter of fact, `PUT /v1/admin/peers/<id>` does already support peer renaming (you can see all the allowed fields to edit on that endpoint at https://github.com/tonarino/innernet/blob/main/server/src/db/peer.rs#L133), so no server changes should be required to add that command to the client.

In the mean time you can either construct your own HTTP request to the server or edit the SQLite database on the server side directly. They should be roughly the same, with a slight preference for the HTTP API since it does validation of the hostname string that the SQLite checks won't do.

**Comment by kbknapp** [comment]
I don't mind putting in a PR for this if there is appetite to enable this feature through the CLI.

**Comment by mcginty** [comment]
@kbknapp that would be great, I think it's a useful feature to have.
